# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20170302_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_class',
            field=models.SmallIntegerField(choices=[(1, '\u5355\u9009\u9898'), (2, '\u591a\u9009\u9898'), (3, '\u5224\u65ad\u9898'), (4, '\u7b80\u7b54\u9898')], verbose_name='\u9898\u76ee\u7c7b\u578b'),
        ),
    ]
